version: "3.8"

services:
  app:
    build: .
    container_name: go-server-app
    ports:
      - "8080:8080"
    depends_on:
      db-master:
        condition: service_healthy
      # db-slave-1:
      #   condition: service_healthy
      # db-slave-2:
      #   condition: service_healthy
      db-migrate:
        condition: service_completed_successfully
      server_tarantool:
        condition: service_started
      rabbitmq:
        condition: service_started
    env_file:
      - .env
    networks:
      - pgnet

  db-master:
    image: postgres:16
    container_name: pgmaster
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - "$PWD/volumes/pgmaster/:/var/lib/postgresql/data"
    networks:
      - pgnet

  # db-slave-1:
  #   image: postgres:16
  #   container_name: pgslave
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "15432:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 5
  #   volumes:
  #     - "$PWD/volumes/pgslave/:/var/lib/postgresql/data"
  #   networks:
  #     - pgnet

  # db-slave-2:
  #   image: postgres:16
  #   container_name: pgasyncslave
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "25432:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 5
  #   volumes:
  #     - "$PWD/volumes/pgasyncslave/:/var/lib/postgresql/data"
  #   networks:
  #     - pgnet

  db-migrate:
    build:
      context: ./scripts
      dockerfile: Dockerfile
    container_name: goose-migrate
    depends_on:
      - db-master
      # - db-slave-1
      # - db-slave-2
    volumes:
      - ./migrations:/migrations
      - ./scripts:/scripts
    working_dir: /scripts
    entrypoint: ["/bin/sh", "wait-and-migrate.sh"]
    networks:
      - pgnet

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rmq_user
      RABBITMQ_DEFAULT_PASS: rmq_password
    volumes:
      - "$PWD/volumes/rabbitmq/:/var/lib/rabbitmq"
    networks:
      - pgnet

  server_tarantool:
    image: "tarantool/tarantool:3.5.0"
    container_name: server_tarantool
    ports:
      - "13301:3301"
      - "18081:8081"
    environment:
      TZ: UTC
    volumes:
      - "$PWD/volumes/tarantool/:/var/lib/tarantool"
      - "$PWD/tarantool:/opt/tarantool"
    command: ["tarantool", "/opt/tarantool/init.lua"]
    networks:
      - pgnet
      
networks:
  pgnet:
    driver: bridge
    ipam:
          driver: default
          config:
            - subnet: "172.19.0.0/16"
