version: "3.8"

services:
  app:
    build: .
    container_name: go-server-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      db-migrate:
        condition: service_completed_successfully
    env_file:
      - .env


  db:
    image: postgres:16
    container_name: go-server-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  db-migrate:
    build:
      context: ./scripts
      dockerfile: Dockerfile
    container_name: goose-migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
      - ./scripts:/scripts
    working_dir: /scripts
    entrypoint: ["/bin/sh", "wait-and-migrate.sh"]